name: Build

on:
  push:
    paths:
      - '.github/workflows/build.yaml'
  schedule:
    - cron: '0 0 * * *' # every day in 00:00
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  vars:
    name: Generation vars
    runs-on: ubuntu-latest
    outputs:
      prefix-test: ${{ steps.basic.outputs.prefix_test }}
      basic-image: ${{ steps.basic.outputs.basic_image }}
      basic-tag: ${{ steps.basic.outputs.basic_tag }}
    steps:
      - name: Get last version k0s
        id: last_tag
        run: |
          version=$(curl -L --fail "https://hub.docker.com/v2/repositories/${{ vars.BASE_IMAGE }}/tags/?page_size=1000&name=3.18" | \
          	jq '.results | .[] | .name' -r | \
          	sed 's/${{ matrix.tag_prefix }}//' | \
          	sort --version-sort | \
          	tail -n 1)
          echo "value=$version" >> $GITHUB_OUTPUT

      - name: Create basic vars
        id: basic
        run: |
          echo "prefix_test=test" >> $GITHUB_OUTPUT
          echo "basic_image=${{ vars.BASE_IMAGE }}" >> $GITHUB_OUTPUT
          echo "basic_tag=${{ steps.last_tag.outputs.value }}" >> $GITHUB_OUTPUT
      

  run_test:
    needs: [ vars ]
    name: Run workflow - test
    uses: text-adi/base-image/.github/workflows/test.yaml@dev
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-run_manual
      cancel-in-progress: true

  build_and_push:
    needs: [ vars, run_test ]
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set test prefix
        id: image_tag_test
        run: |
          echo "value=${{ secrets.DOCKER_USERNAME }}/${{ vars.APP_NAME }}:${{ needs.vars.outputs.prefix-test }}" >> $GITHUB_OUTPUT

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          file: Dockerfile
          load: true
          provenance: false
          target: local
          build-args: |
            BASE_IMAGE=${{ needs.vars.outputs.basic-image }}:${{ needs.vars.outputs.basic-tag }}
          tags: |
            ${{ steps.image_tag_test.outputs.value }}
          cache-to: type=gha,mode=max

      - name: Get tool version
        id: version
        run: |
          echo "kubectl=$(docker run --rm ${{ steps.image_tag_test.outputs.value }} kubectl version --client -o json | jq '.clientVersion.gitVersion' | tr -d 'v"')" >> $GITHUB_OUTPUT

      - name: Check kubectl and awscli version
        run: |
          echo "kubectl: '${{ steps.version.outputs.kubectl }}'"

      - name: Create image tag
        id: image_tag_basic
        run: |
          echo "value=${{ secrets.DOCKER_USERNAME }}/${{ vars.APP_NAME }}:${{ steps.version.outputs.kubectl }}" >> "$GITHUB_OUTPUT"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          file: Dockerfile
          push: true
          provenance: false
          target: local
          build-args: |
            BASE_IMAGE=${{ needs.vars.outputs.basic-image }}:${{ needs.vars.outputs.basic-tag }}
          tags: |
            ${{ steps.image_tag_basic.outputs.value }}
          cache-from: type=gha
